server:
  port: 8080

spring:
  application:
    name: devices-api

  datasource:
    url: jdbc:postgresql://db:5432/devices
    username: user
    password: pass

    redis:
      host: redis
      port: 6379

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus
    metrics:
      tags:
        application: devices-api
